# Generated by Django 4.2.7 on 2023-11-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_userprofile_admission_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_email',
        ),
    ]
