# Generated by Django 4.0.4 on 2023-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_student_groups_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
