# Generated by Django 4.0.4 on 2023-09-14 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_student_groups_remove_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bot_response',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
